[package]
name = "entropy"
version = "0.1.0"
authors = ["Francis Nicholson <francisnicholson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
anyhow = "*"
chrono = "*"
rand = "*"
